### ISSUE TITLE
Clarifications on the Dataset and Dataloader

### ISSUE THREAD

**Issue by albertotono** [Yueeey/deepsketch#3]
I was able to download the dataset, but it is a bit confusing. 

![Screenshot from 2022-05-26 23-55-33](https://user-images.githubusercontent.com/11828200/170647479-0677d3d7-0dd4-4209-abb7-e06e65ef142c.png)

![Screenshot from 2022-05-26 23-55-42](https://user-images.githubusercontent.com/11828200/170647474-0ef166b0-efd3-4d79-8179-ad942b89e963.png)

![Screenshot from 2022-05-26 23-55-47](https://user-images.githubusercontent.com/11828200/170647471-5afc3f42-db2c-488d-af68-6ac17e9b0bcf.png)

I saw a lot of `import pudb; pu.db` so I guess you also debug this part. 

I am not sure what folder structure it is supposted to take, also what is the difference between 
```
anc_folder: naive_set
other_folder: naive_set
```

in onet.yaml?? I don't see any `anc_folder` in the config. 

I got this error 

```
raceback (most recent call last):
  File "train.py", line 150, in <module>
    for batch in train_loader:
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/alberto/Documents/deepsketch/reconstruction/im2mesh/data/core.py", line 156, in __getitem__
    field_data = field.load(model_path, idx, c_idx)
  File "/home/alberto/Documents/deepsketch/reconstruction/im2mesh/data/fields.py", line 94, in load
    idx_img = random.randint(0, len(files_base)-1)
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/alberto/Documents/deepsketch/reconstruction/im2mesh/data/core.py", line 160, in __getitem__
    field_data = field.load(model_path, idx, c_idx)
  File "/home/alberto/Documents/deepsketch/reconstruction/im2mesh/data/fields.py", line 94, in load
    idx_img = random.randint(0, len(files_base)-1)
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/home/alberto/anaconda3/envs/mesh_funcspace_ds/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
```

any idea why is this happening? I think the dataloader is empty. but I am not sure what folder structure is expecting. 

Thanks in advance

**Comment by yinkalario** [comment]
Okay thanks.
